name = "TensorFunction"
uuid = "b5bf068d-715e-43a4-ab5f-ce272ccd184b"
authors = ["KwatMDPhD <kwat.me@icloud.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
